export enum GameStatus {
  MENU,
  PLAYING,
  GAME_OVER
}

export interface Vector3 {
  x: number;
  y: number;
  z: number;
}

export interface Entity {
  id: string;
  pos: Vector3;
  vel: Vector3;
  width: number;
  height: number;
  color: string;
  isDead: boolean;
  type: 'player' | 'enemy';
  flavorText?: string; // Generated by Gemini
}

export interface Player extends Entity {
  hp: number;
  maxHp: number;
  isGrounded: boolean;
  isPunching: boolean;
  punchCooldown: number;
  invincibleTime: number;
  facingRight: boolean;
}

export interface Enemy extends Entity {
  speed: number;
  aggroRange: number;
  attackCooldown: number;
  shape: 'box' | 'blob' | 'spiky';
}

export interface Particle {
  id: string;
  pos: Vector3;
  vel: Vector3;
  life: number;
  color: string;
  size: number;
}